/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#a44100",
        "secondary-container": "#dae2fd",
        "surface-container-low": "#f5f2ff",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-background": "#1b1b24",
        "on-primary-fixed-variant": "#3323cc",
        "error": "#ba1a1a",
        "secondary-fixed": "#dae2fd",
        "outline": "#777587",
        "inverse-surface": "#302f39",
        "background": "#fcf8ff",
        "on-error-container": "#93000a",
        "surface-container": "#f0ecf9",
        "tertiary-fixed-dim": "#ffb695",
        "outline-variant": "#c7c4d8",
        "surface": "#fcf8ff",
        "tertiary": "#7e3000",
        "surface-container-highest": "#e4e1ee",
        "surface-bright": "#fcf8ff",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-dim": "#dcd8e5",
        "primary": "#3525cd",
        "primary-container": "#4f46e5",
        "on-tertiary-fixed": "#351000",
        "on-tertiary-container": "#ffd2be",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-primary": "#c3c0ff",
        "on-primary-fixed": "#0f0069",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#131b2e",
        "on-primary": "#ffffff",
        "primary-fixed": "#e2dfff",
        "tertiary-fixed": "#ffdbcc",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#464555",
        "surface-tint": "#4d44e3",
        "surface-container-high": "#eae6f4",
        "inverse-on-surface": "#f3effc",
        "on-surface": "#1b1b24",
        "on-secondary": "#ffffff",
        "secondary": "#565e74",
        "on-secondary-container": "#5c647a",
        "primary-fixed-dim": "#c3c0ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "gutter": "24px",
        "container-max": "1280px",
        "base": "8px",
        "stack-md": "24px",
        "margin-mobile": "16px",
        "stack-sm": "12px",
        "stack-lg": "48px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
